TRAIN:
  USE_FLIPPED: True
  USE_CACHE: True
  CACHE_PATH: dataset/cache
  TRAIN_PATH: dataset/for_train
  COORDINAE_NUM: 4
  WEIGHT_DECAY: 0.0005
  RPN_NEGATIVE_OVERLAP: 0.3
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_FG_FRACTION: 0.5
  RPN_BATCHSIZE: 300
TEST:

