COMMON:
  CKPT: checkpoints/checkpoint
PREPARE:
  SLOP_THRESHOLD: 1
TRAIN:
  USE_FLIPPED: False
  USE_CACHED: False
  CACHE_PATH: dataset/cache
  TRAIN_PATH: dataset/for_train
  COORDINATE_NUM: 4
  IMS_BATCH_SIZE: 1  # 每轮图片的数目
  BATCH_SIZE: 300 # 每轮生成的anchor个数
  FG_FRACTION: 0.25
  SCALES: [600,]
  PIXEL_MEANS: [[[102.9801, 115.9465, 122.7717]]]
  MAX_SIZE: 1000
  WEIGHT_DECAY: 0.0005
  RPN_NEGATIVE_OVERLAP: 0.2
  RPN_POSITIVE_OVERLAP: 1.1
  RPN_FG_FRACTION: 0.5
  RPN_BATCHSIZE: 256
  OHEM: False
  LEARNING_RATE: 0.00001
  SOLVER: "Momentum"
  MOMENTUM: 0.9
  STEPSIZE: 30000
  GAMMA: 0.1
  DISPLAY: 100
  MAX_ITER: 50000
  SNAPSHOT_ITERS: 1000
  RANDOM_DOWNSAMPLE: Ture
TEST:
  DETECT_MODE: "H"
  DATA_DIR: dataset/for_test
  RESULT_DIR: data/results
  SCALES: 600
  SCALE: 600
  MAX_SCALE: 1200
  TEXT_PROPOSALS_WIDTH: 16
  MIN_NUM_PROPOSALS: 2
  MIN_RATIO: 0.5
  LINE_MIN_SCORE: 0.9
  MAX_HORIZONTAL_GAP: 50
  TEXT_PROPOSALS_MIN_SCORE: 0.7
  TEXT_PROPOSALS_NMS_THRESH: 0.2
  MIN_V_OVERLAPS: 0.7
  MIN_SIZE_SIM: 0.7
