PREPARE:
  SLOP_THRESHOLD: 1
TRAIN:
  USE_FLIPPED: True
  USE_CACHED: False
  CACHE_PATH: dataset/cache
  TRAIN_PATH: dataset/for_train
  COORDINATE_NUM: 4
  IMS_BATCH_SIZE: 1  # 每轮图片的数目
  BATCH_SIZE: 300 # 每轮生成的anchor个数
  FG_FRACTION: 0.25
  SCALES: 600
  PIXEL_MEANS: [[[102.9801, 115.9465, 122.7717]]]
  MAX_SIZE: 1000
  WEIGHT_DECAY: 0.0005
TEST:

